platform :ios, '12.2'
install! 'cocoapods', :integrate_targets => false
target 'ObjectiveSharpieIntegration' do
  use_frameworks!
end
pod 'CardScan', :git => 'git@github.com:getbouncer/cardscan-ios.git', :tag => '1.0.4034'
pod 'CardScan/Stripe', :git => 'git@github.com:getbouncer/cardscan-ios.git', :tag => '1.0.4034'
